### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by kongupradeep** [Avishaidev/camera-preview-video#3]
i can't run this project it will not working 

installing "cordova-plugin-camera-preview" for android
Android Studio project detected
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-camera-preview': Error: Uh oh!
ENOENT: no such file or directory, open '/home/pk/Documents/examples/camera-preview-video/plugins/cordova-plugin-camera-preview/www/CameraPreview.js'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at install (/home/pk/Documents/examples/camera-preview-video/platforms/android/cordova/lib/pluginHandlers.js:187:36)
    at ActionStack.process (/home/pk/Documents/examples/camera-preview-video/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/home/pk/Documents/examples/camera-preview-video/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/home/pk/Documents/examples/camera-preview-video/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at /home/pk/Documents/examples/camera-preview-video/platforms/android/cordova/Api.js:247:74
    at _fulfilled (/home/pk/Documents/examples/camera-preview-video/platforms/android/cordova/node_modules/q/q.js:834:54)
    at /home/pk/Documents/examples/camera-preview-video/platforms/android/cordova/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/home/pk/Documents/examples/camera-preview-video/platforms/android/cordova/node_modules/q/q.js:796:13)
Uh oh!
ENOENT: no such file or directory, open '/home/pk/Documents/examples/camera-preview-video/plugins/cordova-plugin-camera-preview/www/CameraPreview.js'

can you help you this for one?

**Comment by Peixer** [comment]
@kongupradeep add the file /www/CameraPreview.js in your plugin, like my fork https://github.com/icetec-solutions/cordova-plugin-camera-preview

**Comment by Avishaidev** [comment]
Files are updated, You can try again.
Let me know if you need some.
Thanks
